# Generated by Django 3.2.9 on 2022-03-12 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='fileuploadinfo',
            name='pickle',
            field=picklefield.fields.PickledObjectField(blank=True, db_column='Pickle', editable=False, max_length=255, null=True),
        ),
        
    ]
