# Generated by Django 3.2.9 on 2022-03-20 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0003_apprenticeshipregistration_averagetestscores_countyconnectioninfo_districts_engagementinfo_expenditu'),
    ]

    operations = [
       
        migrations.CreateModel(
            name='SchoolBoardAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(blank=True, db_column='Board', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=255, null=True)),
                ('grade_ten_osslt_results', models.FloatField(blank=True, db_column='GradeTenOsslt', null=True)),
                ('grade_six_eqao_results', models.FloatField(blank=True, db_column='GradeSixEqao', null=True)),
                ('four_year_graduation_rate', models.FloatField(blank=True, db_column='FourYearGraduationRate', null=True)),
            ],
            options={
                'db_table': 'board_achievements',
            },
        ),
        migrations.CreateModel(
            name='SpecialEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, db_column='AcademicYear', max_length=255, null=True)),
                ('exceptionality', models.CharField(blank=True, db_column='Exceptionality', max_length=255, null=True)),
                ('elementary_enrollment', models.FloatField(blank=True, db_column='ElementaryEnrollment', null=True)),
                ('secondary_enrollment', models.FloatField(blank=True, db_column='SecondaryEnrollment', null=True)),
                ('total_enrollment', models.FloatField(blank=True, db_column='TotalEnrollment', null=True)),
            ],
            options={
                'db_table': 'special_education',
            },
        ),
        
    ]
