# Generated by Django 4.0.3 on 2022-03-31 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0004_apprenticeshipregistration_averagetestscores_countyconnectioninfo_districts_engagementinfo_expenditu'),
    ]

    operations = [
       
        migrations.CreateModel(
            name='PdfSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_keyword', models.CharField(blank=True, db_column='Search', max_length=255, null=True)),
                ('data', picklefield.fields.PickledObjectField(blank=True, db_column='Data', editable=False, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'pdf_summary',
            },
        ), 
    ]
