# Generated by Django 4.0.3 on 2022-04-21 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0005_apprenticeshipregistration_averagetestscores_and_more'),
    ]

    operations = [
      
        migrations.CreateModel(
            name='PolicyMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, db_column='FirstName', max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, db_column='LastName', max_length=20, null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=20, null=True)),
            ],
            options={
                'db_table': 'policymaker',
            },
        ),

        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, db_column='FirstName', max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, db_column='LastName', max_length=20, null=True)),
                ('school', models.CharField(blank=True, db_column='School', max_length=20, null=True)),
                ('grade', models.IntegerField(blank=True, db_column='Grade', max_length=20, null=True)),
                ('student_number', models.IntegerField(blank=True, db_column='Identification', max_length=30, null=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),

    ]
