# Generated by Django 4.0.3 on 2022-04-22 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0006_apprenticeshipregistration_averagetestscores_and_more'),
    ]

    operations = [


 
    ]
