# Generated by Django 4.0.3 on 2022-04-22 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0009_alter_hotspot_download_alter_hotspot_upload'),
    ]

    operations = [
      
   
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, db_column='Tweet', max_length=2000, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=20, null=True)),
                ('url', models.CharField(blank=True, db_column='url', max_length=150, null=True)),
                ('retweets', models.IntegerField(blank=True, db_column='Retweets', max_length=5, null=True)),
                ('likes', models.IntegerField(blank=True, db_column='Likes', max_length=5, null=True)),
                ('date', models.CharField(blank=True, db_column='date', max_length=20, null=True)),
            ],
            options={
                'db_table': 'tweets',
            },
        )


    ]
