# Generated by Django 4.0.3 on 2022-04-22 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0010_apprenticeshipregistration_averagetestscores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='GraphName', max_length=100, null=True)),
                ('text', models.TextField(blank=True, db_column='text', max_length=100000, null=True)),
            ],
            options={
                'db_table': 'analysis',
            },
        ),

    ]
