# Generated by Django 3.2.9 on 2021-11-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.IntegerField(blank=True, db_column='DistrictID', null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=255, null=True)),
                ('locale', models.CharField(blank=True, db_column='Locale', max_length=255, null=True)),
                ('pct_black_hispanic', models.IntegerField(blank=True, db_column='Pct_ethnicity', null=True)),
                ('county_connection', models.IntegerField(blank=True, db_column='County_connection', null=True)),
                ('pp_total_raw', models.IntegerField(blank=True, db_column='PP_total_raw', null=True)),
            ],
            options={
                'db_table': 'district_info',
            },
        ),
    ]
