# Generated by Django 3.2.9 on 2022-02-13 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='RatingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, db_column='Rating', null=True)),
                ('wifiquality', models.IntegerField(blank=True, db_column='Quality', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('placeaddress', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
            ],
            options={
                'db_table': 'ratingwifi_info',
            },
        ),
        
    ]
