# Generated by Django 3.2.9 on 2022-02-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='engagementinfo',
            name='district_id',
            field=models.IntegerField(blank=True, db_column='district_id', null=True),
        ),
        migrations.AddField(
            model_name='engagementinfo',
            name='timestamp',
            field=models.CharField(blank=True, db_column='timestamp', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='engagementinfo',
            name='engagement_index',
            field=models.FloatField(blank=True, db_column='engagement_index', null=True),
        ),
        migrations.AlterField(
            model_name='engagementinfo',
            name='lp_id',
            field=models.IntegerField(blank=True, db_column='lp_id', null=True),
        ),
        migrations.AlterField(
            model_name='engagementinfo',
            name='pct_access',
            field=models.FloatField(blank=True, db_column='pct_access', null=True),
        ),
    ]
