# Generated by Django 3.2.9 on 2022-03-12 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0001_initial'),
    ]

    operations = [
         migrations.CreateModel(
            name='FileUploadInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, db_column='Filename', max_length=255, null=True)),
                ('pickle', models.CharField(blank=True, db_column='Pickle', max_length=1200, null=True)),
                ('user_name', models.CharField(blank=True, db_column='Username', max_length=255, null=True)),
            ],
            options={
                'db_table': 'file_upload',
            },
        ),
    ]
