# Generated by Django 3.2.9 on 2021-11-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districts',
            name='county_connection',
            field=models.FloatField(blank=True, db_column='County_connection', null=True),
        ),
        migrations.AlterField(
            model_name='districts',
            name='district_id',
            field=models.FloatField(blank=True, db_column='DistrictID', null=True),
        ),
        migrations.AlterField(
            model_name='districts',
            name='pct_black_hispanic',
            field=models.FloatField(blank=True, db_column='Pct_ethnicity', null=True),
        ),
        migrations.AlterField(
            model_name='districts',
            name='pp_total_raw',
            field=models.FloatField(blank=True, db_column='PP_total_raw', null=True),
        ),
    ]
