# Generated by Django 3.2.9 on 2021-11-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20211115_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lpid', models.IntegerField(blank=True, db_column='Lpid', null=True)),
                ('product_name', models.CharField(blank=True, db_column='Product Name', max_length=255, null=True)),
                ('provider_name', models.CharField(blank=True, db_column='Provider', max_length=255, null=True)),
                ('sector', models.CharField(blank=True, db_column='Sector', max_length=255, null=True)),
                ('primary_essential', models.CharField(blank=True, db_column='Primary Essential Function', max_length=255, null=True)),
            ],
            options={
                'db_table': 'products_info',
            },
        ),
    ]
