# Generated by Django 3.2.5 on 2022-03-07 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0002_postsecondaryenrollment_productsinfo_ratinginfo_studentforminfo_userprofile'),
    ]

    operations = [

    ]
