# Generated by Django 3.2.9 on 2021-11-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_productsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinfo',
            name='url',
            field=models.CharField(blank=True, db_column='URL', max_length=255, null=True),
        ),
    ]
