# Generated by Django 3.2.5 on 2022-03-07 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0003_countyconnectioninfo_districts_engagementinfo_postsecondaryenrollment_productsinfo_ratinginfo_studen'),
    ]

    operations = [

        migrations.CreateModel(
            name='ExpenditureColleges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.CharField(blank=True, db_column='ReferenceDate', max_length=255, null=True)),
                ('geo', models.CharField(blank=True, db_column='Geo', max_length=255, null=True)),
                ('types_of_expenditure', models.CharField(blank=True, db_column='Types', max_length=255, null=True)),
                ('value', models.FloatField(blank=True, db_column='Value', null=True)),
            ],
            options={
                'db_table': 'expenditure_colleges',
            },
        ),


        ]

