# Generated by Django 3.2.9 on 2021-11-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_auto_20211115_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, db_column='Time', max_length=255, null=True)),
                ('lp_id', models.IntegerField(blank=True, db_column='Lp_id', null=True)),
                ('pct_access', models.FloatField(blank=True, db_column='Pct_access', null=True)),
                ('engagement_index', models.FloatField(blank=True, db_column='Engagement_index', null=True)),
            ],
            options={
                'db_table': 'engagement_info',
            },
        ),
    ]
