# Generated by Django 3.2.5 on 2022-03-07 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='CountyConnectionInfo',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('county_code', models.IntegerField(blank=True, db_column='County_code', null=True)),
        #         ('state', models.CharField(blank=True, db_column='State', max_length=255, null=True)),
        #         ('county_name', models.CharField(blank=True, db_column='County_name', max_length=255, null=True)),
        #         ('ratio', models.FloatField(blank=True, db_column='Ratio', null=True)),
        #     ],
        #     options={
        #         'db_table': 'county_connection',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Districts',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('district_id', models.FloatField(blank=True, db_column='DistrictID', null=True)),
        #         ('state', models.CharField(blank=True, db_column='State', max_length=255, null=True)),
        #         ('locale', models.CharField(blank=True, db_column='Locale', max_length=255, null=True)),
        #         ('pct_black_hispanic', models.FloatField(blank=True, db_column='Pct_ethnicity', null=True)),
        #         ('free_reduced', models.FloatField(blank=True, db_column='Free_reduced', null=True)),
        #         ('county_connection', models.FloatField(blank=True, db_column='County_connection', null=True)),
        #         ('pp_total_raw', models.FloatField(blank=True, db_column='PP_total_raw', null=True)),
        #     ],
        #     options={
        #         'db_table': 'district_info',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='EngagementInfo',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('district_id', models.IntegerField(blank=True, db_column='district_id', null=True)),
        #         ('timestamp', models.CharField(blank=True, db_column='timestamp', max_length=255, null=True)),
        #         ('lp_id', models.IntegerField(blank=True, db_column='lp_id', null=True)),
        #         ('pct_access', models.FloatField(blank=True, db_column='pct_access', null=True)),
        #         ('engagement_index', models.FloatField(blank=True, db_column='engagement_index', null=True)),
        #     ],
        #     options={
        #         'db_table': 'engagement_info',
        #     },
        # ),
        migrations.CreateModel(
            name='LabourForce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.CharField(blank=True, db_column='ReferenceDate', max_length=255, null=True)),
                ('age_group', models.CharField(blank=True, db_column='AgeGroup', max_length=255, null=True)),
                ('labour_force_status', models.CharField(blank=True, db_column='LabourForceStatus', max_length=255, null=True)),
                ('value', models.FloatField(blank=True, db_column='Value', null=True)),
            ],
            options={
                'db_table': 'labour_force',
            },
        ),
        # migrations.CreateModel(
        #     name='PostSecondaryEnrollment',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('reference_date', models.CharField(blank=True, db_column='ReferenceDate', max_length=255, null=True)),
        #         ('geo', models.CharField(blank=True, db_column='GEO', max_length=255, null=True)),
        #         ('institution_type', models.CharField(blank=True, db_column='InstitutionType', max_length=255, null=True)),
        #         ('gender', models.CharField(blank=True, db_column='Gender', max_length=255, null=True)),
        #         ('value', models.FloatField(blank=True, db_column='Value', null=True)),
        #     ],
        #     options={
        #         'db_table': 'postsecondary_enrollment',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='ProductsInfo',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('lpid', models.IntegerField(blank=True, db_column='Lpid', null=True)),
        #         ('url', models.CharField(blank=True, db_column='URL', max_length=255, null=True)),
        #         ('product_name', models.CharField(blank=True, db_column='Product_Name', max_length=255, null=True)),
        #         ('provider_name', models.CharField(blank=True, db_column='Provider', max_length=255, null=True)),
        #         ('sector', models.CharField(blank=True, db_column='Sector', max_length=255, null=True)),
        #         ('primary_essential', models.CharField(blank=True, db_column='Primary_Essential_Function', max_length=255, null=True)),
        #     ],
        #     options={
        #         'db_table': 'products_info',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='RatingInfo',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('rating', models.IntegerField(blank=True, db_column='Rating', null=True)),
        #         ('wifiquality', models.IntegerField(blank=True, db_column='Quality', null=True)),
        #         ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
        #         ('placeaddress', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
        #     ],
        #     options={
        #         'db_table': 'ratingwifi_info',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='StudentFormInfo',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('province', models.CharField(blank=True, db_column='Province', max_length=255, null=True)),
        #         ('schoolgrade', models.IntegerField(blank=True, db_column='Grade', null=True)),
        #         ('testscore', models.IntegerField(blank=True, db_column='Testscore', null=True)),
        #         ('attendancepercentage', models.IntegerField(blank=True, db_column='Attendance', null=True)),
        #         ('device', models.CharField(blank=True, db_column='Device', max_length=255, null=True)),
        #         ('studentworkstatus', models.CharField(blank=True, db_column='Work', max_length=255, null=True)),
        #         ('parentssalary', models.CharField(blank=True, db_column='PSalary', max_length=255, null=True)),
        #         ('wifi', models.CharField(blank=True, db_column='Wifi', max_length=255, null=True)),
        #         ('wificompany', models.CharField(blank=True, db_column='WifiCompany', max_length=255, null=True)),
        #         ('wifispeed', models.CharField(blank=True, db_column='WifiSpeed', max_length=255, null=True)),
        #     ],
        #     options={
        #         'db_table': 'studentform_info',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='UserProfile',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('user_type', models.CharField(max_length=12)),
        #         ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
    ]
